# ----------------------------------------
# DATA PROPERTIES
# ----------------------------------------


spring:
  # DATASOURCE
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fire-hose-service
  jpa:
    hibernate:
      ddl-auto: update
  #Mail
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: nibucloud@gmail.com
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
    test-connection: true
  flyway:
    enabled: false

server:
  servlet:
    context-path: /fire-hose-management
  port: 8085
